//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackStone_Expenses.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Expens
    {
        public int id { get; set; }
        [Required]
        public double Amount { get; set; }
        [Required]
        public string Month { get; set; }
        [Range(1900,3000)]
        [Required]
        public string year { get; set; }
    }
}
