//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackStone_Expenses.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expens
    {
        public int id { get; set; }
        public double Amount { get; set; }
        public string Month { get; set; }
        public string year { get; set; }
    }
}
